name: metacurriculum
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - ale-py==0.8.0
      - antlr4-python3-runtime==4.9.3
      - autorom==0.4.2
      - autorom-accept-rom-license==0.5.5
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.38.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium-notices==0.0.1
      - hydra-core==1.3.1
      - idna==3.4
      - importlib-metadata==4.13.0
      - importlib-resources==5.10.2
      - jax-jumpy==0.2.0
      - kiwisolver==1.4.4
      - libtorrent==2.0.7
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.7.0
      - minatar==1.0.11
      - minigrid==2.1.0
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.0
      - seaborn==0.12.2
      - shimmy==0.2.0
      - six==1.16.0
      - stable-baselines3==1.7.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - torch==1.13.1
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - werkzeug==2.2.3
      - zipp==3.13.0
