_target_: factories.alg.dqn.make_alg
id: dqn

rparams:
  total_timesteps: 100000
  batch_size: 128

hparams:
  learning_rate: 0.0025
  buffer_size: 10000
  gamma: 0.99
  num_steps: 1
  tau: 1.0
  target_network_frequency: 500
  start_e: 1
  end_e: 0.05
  exploration_fraction: 0.5
  learning_starts: 10000
  train_frequency: 10